param(
  [ValidateSet('simulated', 'testnet')]
  [string]$Mode = 'testnet',
  [switch]$Apply
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$apiEnvLocalPath = Join-Path $repoRoot 'services/api/.env.local'
$apiEnvPath = Join-Path $repoRoot 'services/api/.env'
$webEnvLocalPath = Join-Path $repoRoot 'apps/web/.env.local'
$webEnvPath = Join-Path $repoRoot 'apps/web/.env'

function Read-DotEnvFile {
  param([string]$Path)
  $result = @{}
  if (-not (Test-Path $Path)) { return $result }

  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
    $idx = $trimmed.IndexOf('=')
    if ($idx -lt 1) { continue }

    $key = $trimmed.Substring(0, $idx).Trim()
    $value = $trimmed.Substring($idx + 1).Trim()

    if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }

    $result[$key] = $value
  }

  return $result
}

function Get-Value {
  param(
    [string]$Name,
    [hashtable]$ApiLocal,
    [hashtable]$Api,
    [hashtable]$WebLocal,
    [hashtable]$Web
  )

  $envValue = [Environment]::GetEnvironmentVariable($Name)
  if (-not [string]::IsNullOrWhiteSpace($envValue)) { return $envValue }
  if ($ApiLocal.ContainsKey($Name)) { return $ApiLocal[$Name] }
  if ($Api.ContainsKey($Name)) { return $Api[$Name] }
  if ($WebLocal.ContainsKey($Name)) { return $WebLocal[$Name] }
  if ($Web.ContainsKey($Name)) { return $Web[$Name] }
  return ''
}

function Is-HexAddress {
  param([string]$Value)
  return $Value -match '^0x[a-fA-F0-9]{40}$'
}

function Is-HexPrivateKey {
  param([string]$Value)
  return $Value -match '^0x[a-fA-F0-9]{64}$'
}

function Add-Check {
  param(
    [string]$Name,
    [bool]$Ok,
    [string]$Detail
  )
  return [pscustomobject]@{
    Check = $Name
    Status = $(if ($Ok) { 'PASS' } else { 'FAIL' })
    Detail = $Detail
  }
}

function Has-FilePathValue {
  param([string]$Value)
  return -not [string]::IsNullOrWhiteSpace($Value)
}

function Write-ApiEnvLocal {
  param(
    [string]$Path,
    [string]$Mode,
    [hashtable]$Values
  )

  $lines = @(
    '# Generated by scripts/testnet-readiness.ps1',
    "# Mode: $Mode",
    'PORT=3003',
    "API_KEY=$($Values['API_KEY'])",
    "STARTUP_STRICT=$($Values['STARTUP_STRICT'])",
    "USE_SNARKJS=$($Values['USE_SNARKJS'])",
    "SNARK_WASM_PATH=$($Values['SNARK_WASM_PATH'])",
    "SNARK_ZKEY_PATH=$($Values['SNARK_ZKEY_PATH'])",
    "SNARK_VKEY_PATH=$($Values['SNARK_VKEY_PATH'])",
    '',
    "CORS_ALLOWED_ORIGINS=$($Values['CORS_ALLOWED_ORIGINS'])",
    "CORS_ALLOW_CREDENTIALS=$($Values['CORS_ALLOW_CREDENTIALS'])"
  )

  if ($Mode -eq 'testnet') {
    $lines += @(
      "RPC_URL=$($Values['RPC_URL'])",
      "PRIVATE_KEY=$($Values['PRIVATE_KEY'])",
      "SBT_CONTRACT_ADDRESS=$($Values['SBT_CONTRACT_ADDRESS'])",
      "TRUST_REGISTRY_ADDRESS=$($Values['TRUST_REGISTRY_ADDRESS'])",
      "AGE_VERIFIER_ADDRESS=$($Values['AGE_VERIFIER_ADDRESS'])",
      "REQUIRE_AGE_VERIFIER=$($Values['REQUIRE_AGE_VERIFIER'])"
    )
  } else {
    $lines += @(
      'RPC_URL=',
      'PRIVATE_KEY=',
      'SBT_CONTRACT_ADDRESS=',
      'TRUST_REGISTRY_ADDRESS=',
      'AGE_VERIFIER_ADDRESS=',
      "REQUIRE_AGE_VERIFIER=$($Values['REQUIRE_AGE_VERIFIER'])"
    )
  }

  $lines += @(
    '',
    "LIFEPASS_SSO_JWT_SECRET=$($Values['LIFEPASS_SSO_JWT_SECRET'])",
    "LIFEPASS_SSO_JWT_ISSUER=$($Values['LIFEPASS_SSO_JWT_ISSUER'])",
    "LIFEPASS_SSO_DEFAULT_AUDIENCE=$($Values['LIFEPASS_SSO_DEFAULT_AUDIENCE'])",
    "LIFEPASS_SSO_JWT_EXPIRES_IN=$($Values['LIFEPASS_SSO_JWT_EXPIRES_IN'])",
    '',
    "LIFEPASS_PORTAL_POLICY_JSON=$($Values['LIFEPASS_PORTAL_POLICY_JSON'])",
    "PORTAL_ACCESS_AUDIT_MAX_ROWS=$($Values['PORTAL_ACCESS_AUDIT_MAX_ROWS'])",
    "POLICY_ADMIN_KEY=$($Values['POLICY_ADMIN_KEY'])",
    "POLICY_ADMIN_AUDIT_MAX_ROWS=$($Values['POLICY_ADMIN_AUDIT_MAX_ROWS'])",
    "POLICY_SNAPSHOT_MAX_ROWS=$($Values['POLICY_SNAPSHOT_MAX_ROWS'])",
    "PORTAL_DENY_ALERT_THRESHOLD=$($Values['PORTAL_DENY_ALERT_THRESHOLD'])",
    "PORTAL_DENY_ALERT_WINDOW_MINUTES=$($Values['PORTAL_DENY_ALERT_WINDOW_MINUTES'])",
    "POLICY_TWO_PERSON_REQUIRED=$($Values['POLICY_TWO_PERSON_REQUIRED'])",
    "POLICY_REQUIRED_APPROVALS=$($Values['POLICY_REQUIRED_APPROVALS'])",
    "POLICY_APPROVAL_SIGNING_KEYS_JSON=$($Values['POLICY_APPROVAL_SIGNING_KEYS_JSON'])",
    "POLICY_APPROVAL_MAX_ROWS=$($Values['POLICY_APPROVAL_MAX_ROWS'])",
    '',
    "OPENAI_API_KEY=$($Values['OPENAI_API_KEY'])"
  )

  $content = ($lines -join "`n") + "`n"
  Set-Content -Path $Path -Value $content -Encoding utf8
}

function Write-WebEnvLocal {
  param(
    [string]$Path,
    [string]$Mode,
    [hashtable]$Values
  )

  $projectId = if ($Mode -eq 'testnet') { $Values['NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'] } else { '' }
  $lines = @(
    '# Generated by scripts/testnet-readiness.ps1',
    "# Mode: $Mode",
    "NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$projectId",
    'NEXT_PUBLIC_API_BASE_URL=http://localhost:3003'
  )

  $content = ($lines -join "`n") + "`n"
  Set-Content -Path $Path -Value $content -Encoding utf8
}

$apiLocal = Read-DotEnvFile -Path $apiEnvLocalPath
$api = Read-DotEnvFile -Path $apiEnvPath
$webLocal = Read-DotEnvFile -Path $webEnvLocalPath
$web = Read-DotEnvFile -Path $webEnvPath

$values = @{
  API_KEY = Get-Value -Name 'API_KEY' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  STARTUP_STRICT = Get-Value -Name 'STARTUP_STRICT' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  RPC_URL = Get-Value -Name 'RPC_URL' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  PRIVATE_KEY = Get-Value -Name 'PRIVATE_KEY' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SBT_CONTRACT_ADDRESS = Get-Value -Name 'SBT_CONTRACT_ADDRESS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  TRUST_REGISTRY_ADDRESS = Get-Value -Name 'TRUST_REGISTRY_ADDRESS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  AGE_VERIFIER_ADDRESS = Get-Value -Name 'AGE_VERIFIER_ADDRESS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  REQUIRE_AGE_VERIFIER = Get-Value -Name 'REQUIRE_AGE_VERIFIER' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = Get-Value -Name 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  USE_SNARKJS = Get-Value -Name 'USE_SNARKJS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_WASM_PATH = Get-Value -Name 'SNARK_WASM_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_ZKEY_PATH = Get-Value -Name 'SNARK_ZKEY_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_VKEY_PATH = Get-Value -Name 'SNARK_VKEY_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  CORS_ALLOWED_ORIGINS = Get-Value -Name 'CORS_ALLOWED_ORIGINS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  CORS_ALLOW_CREDENTIALS = Get-Value -Name 'CORS_ALLOW_CREDENTIALS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  LIFEPASS_SSO_JWT_SECRET = Get-Value -Name 'LIFEPASS_SSO_JWT_SECRET' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  LIFEPASS_SSO_JWT_ISSUER = Get-Value -Name 'LIFEPASS_SSO_JWT_ISSUER' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  LIFEPASS_SSO_DEFAULT_AUDIENCE = Get-Value -Name 'LIFEPASS_SSO_DEFAULT_AUDIENCE' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  LIFEPASS_SSO_JWT_EXPIRES_IN = Get-Value -Name 'LIFEPASS_SSO_JWT_EXPIRES_IN' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  LIFEPASS_PORTAL_POLICY_JSON = Get-Value -Name 'LIFEPASS_PORTAL_POLICY_JSON' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  PORTAL_ACCESS_AUDIT_MAX_ROWS = Get-Value -Name 'PORTAL_ACCESS_AUDIT_MAX_ROWS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_ADMIN_KEY = Get-Value -Name 'POLICY_ADMIN_KEY' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_ADMIN_AUDIT_MAX_ROWS = Get-Value -Name 'POLICY_ADMIN_AUDIT_MAX_ROWS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_SNAPSHOT_MAX_ROWS = Get-Value -Name 'POLICY_SNAPSHOT_MAX_ROWS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  PORTAL_DENY_ALERT_THRESHOLD = Get-Value -Name 'PORTAL_DENY_ALERT_THRESHOLD' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  PORTAL_DENY_ALERT_WINDOW_MINUTES = Get-Value -Name 'PORTAL_DENY_ALERT_WINDOW_MINUTES' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_TWO_PERSON_REQUIRED = Get-Value -Name 'POLICY_TWO_PERSON_REQUIRED' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_REQUIRED_APPROVALS = Get-Value -Name 'POLICY_REQUIRED_APPROVALS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_APPROVAL_SIGNING_KEYS_JSON = Get-Value -Name 'POLICY_APPROVAL_SIGNING_KEYS_JSON' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  POLICY_APPROVAL_MAX_ROWS = Get-Value -Name 'POLICY_APPROVAL_MAX_ROWS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  OPENAI_API_KEY = Get-Value -Name 'OPENAI_API_KEY' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
}

if (-not $values['USE_SNARKJS']) {
  $values['USE_SNARKJS'] = '0'
}
if (-not $values['STARTUP_STRICT']) {
  $values['STARTUP_STRICT'] = '1'
}
if (-not $values['REQUIRE_AGE_VERIFIER']) {
  $values['REQUIRE_AGE_VERIFIER'] = '0'
}
if (-not $values['CORS_ALLOW_CREDENTIALS']) {
  $values['CORS_ALLOW_CREDENTIALS'] = '0'
}
if (-not $values['LIFEPASS_SSO_JWT_ISSUER']) {
  $values['LIFEPASS_SSO_JWT_ISSUER'] = 'lifepass-api'
}
if (-not $values['LIFEPASS_SSO_DEFAULT_AUDIENCE']) {
  $values['LIFEPASS_SSO_DEFAULT_AUDIENCE'] = 'zionstack-portals'
}
if (-not $values['LIFEPASS_SSO_JWT_EXPIRES_IN']) {
  $values['LIFEPASS_SSO_JWT_EXPIRES_IN'] = '15m'
}
if (-not $values['PORTAL_ACCESS_AUDIT_MAX_ROWS']) {
  $values['PORTAL_ACCESS_AUDIT_MAX_ROWS'] = '2000'
}
if (-not $values['POLICY_ADMIN_AUDIT_MAX_ROWS']) {
  $values['POLICY_ADMIN_AUDIT_MAX_ROWS'] = '2000'
}
if (-not $values['POLICY_SNAPSHOT_MAX_ROWS']) {
  $values['POLICY_SNAPSHOT_MAX_ROWS'] = '500'
}
if (-not $values['PORTAL_DENY_ALERT_THRESHOLD']) {
  $values['PORTAL_DENY_ALERT_THRESHOLD'] = '10'
}
if (-not $values['PORTAL_DENY_ALERT_WINDOW_MINUTES']) {
  $values['PORTAL_DENY_ALERT_WINDOW_MINUTES'] = '60'
}
if (-not $values['POLICY_TWO_PERSON_REQUIRED']) {
  $values['POLICY_TWO_PERSON_REQUIRED'] = '0'
}
if (-not $values['POLICY_REQUIRED_APPROVALS']) {
  $values['POLICY_REQUIRED_APPROVALS'] = '2'
}
if (-not $values['POLICY_APPROVAL_MAX_ROWS']) {
  $values['POLICY_APPROVAL_MAX_ROWS'] = '2000'
}

$checks = @()

if ($Mode -eq 'simulated') {
  $checks += Add-Check -Name 'RPC_URL empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['RPC_URL'])) -Detail 'Unset RPC_URL to force local simulation.'
  $checks += Add-Check -Name 'PRIVATE_KEY empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['PRIVATE_KEY'])) -Detail 'Unset PRIVATE_KEY to avoid on-chain tx signing.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['SBT_CONTRACT_ADDRESS'])) -Detail 'Unset SBT_CONTRACT_ADDRESS so /sbt/mint uses simulated response.'
} else {
  $checks += Add-Check -Name 'RPC_URL set' -Ok (-not [string]::IsNullOrWhiteSpace($values['RPC_URL'])) -Detail 'Required for testnet JSON-RPC provider.'
  $checks += Add-Check -Name 'PRIVATE_KEY set' -Ok (-not [string]::IsNullOrWhiteSpace($values['PRIVATE_KEY'])) -Detail 'Required for server-side signer.'
  $checks += Add-Check -Name 'PRIVATE_KEY format' -Ok (Is-HexPrivateKey $values['PRIVATE_KEY']) -Detail 'Expected 0x-prefixed 64-byte hex key.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS set' -Ok (-not [string]::IsNullOrWhiteSpace($values['SBT_CONTRACT_ADDRESS'])) -Detail 'Required to mint on-chain.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS format' -Ok (Is-HexAddress $values['SBT_CONTRACT_ADDRESS']) -Detail 'Expected 0x-prefixed 20-byte address.'
  $checks += Add-Check -Name 'WalletConnect project ID set' -Ok (-not [string]::IsNullOrWhiteSpace($values['NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'])) -Detail 'Required for web wallet connection UX.'

  $requireVerifier = $values['REQUIRE_AGE_VERIFIER'] -eq '1'
  $checks += Add-Check -Name 'REQUIRE_AGE_VERIFIER format' -Ok ($values['REQUIRE_AGE_VERIFIER'] -in @('0', '1')) -Detail 'Use 1 to require AGE_VERIFIER_ADDRESS in strict startup/readiness checks.'

  if (-not [string]::IsNullOrWhiteSpace($values['AGE_VERIFIER_ADDRESS'])) {
    $checks += Add-Check -Name 'AGE_VERIFIER_ADDRESS format' -Ok (Is-HexAddress $values['AGE_VERIFIER_ADDRESS']) -Detail 'Must be valid address when provided.'
  } elseif ($requireVerifier) {
    $checks += Add-Check -Name 'AGE_VERIFIER_ADDRESS required' -Ok $false -Detail 'Set AGE_VERIFIER_ADDRESS when REQUIRE_AGE_VERIFIER=1.'
  } else {
    $checks += Add-Check -Name 'AGE_VERIFIER_ADDRESS optional' -Ok $true -Detail 'Not set: /proof/verify-onchain will use local fallback verification.'
  }
}

$useSnark = $values['USE_SNARKJS'] -eq '1'
if ($useSnark) {
  $checks += Add-Check -Name 'SNARK_WASM_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_WASM_PATH']) -Detail 'Required for groth16 witness/proof generation.'
  $checks += Add-Check -Name 'SNARK_ZKEY_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_ZKEY_PATH']) -Detail 'Required proving key for groth16 fullProve.'
  $checks += Add-Check -Name 'SNARK_VKEY_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_VKEY_PATH']) -Detail 'Required verification key for groth16 verify.'
}

Write-Host ""
Write-Host "LifePass Mode Checklist" -ForegroundColor Cyan
Write-Host "Mode: $Mode" -ForegroundColor Cyan
Write-Host ""
$checks | Format-Table -AutoSize

$failed = @($checks | Where-Object { $_.Status -eq 'FAIL' })

if ($Apply) {
  if ($failed.Count -gt 0) {
    Write-Host "" -ForegroundColor Red
    Write-Host "Cannot apply mode because checklist failed." -ForegroundColor Red
    exit 1
  }

  Write-ApiEnvLocal -Path $apiEnvLocalPath -Mode $Mode -Values $values
  Write-WebEnvLocal -Path $webEnvLocalPath -Mode $Mode -Values $values

  Write-Host "" -ForegroundColor Green
  Write-Host "Applied mode '$Mode':" -ForegroundColor Green
  Write-Host "- services/api/.env.local"
  Write-Host "- apps/web/.env.local"
}

Write-Host ""
if ($failed.Count -eq 0) {
  Write-Host 'Checklist status: READY' -ForegroundColor Green
  Write-Host 'Suggested next commands:' -ForegroundColor Green
  Write-Host '1. Set-Location services/api; npm run start'
  Write-Host '2. Set-Location apps/web; npm run dev'
  exit 0
}

Write-Host 'Checklist status: NOT READY' -ForegroundColor Yellow
Write-Host 'Fill missing values and re-run.' -ForegroundColor Yellow
exit 1
