param(
  [ValidateSet('simulated', 'testnet')]
  [string]$Mode = 'testnet',
  [switch]$Apply
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$apiEnvLocalPath = Join-Path $repoRoot 'services/api/.env.local'
$apiEnvPath = Join-Path $repoRoot 'services/api/.env'
$webEnvLocalPath = Join-Path $repoRoot 'apps/web/.env.local'
$webEnvPath = Join-Path $repoRoot 'apps/web/.env'

function Read-DotEnvFile {
  param([string]$Path)
  $result = @{}
  if (-not (Test-Path $Path)) { return $result }

  foreach ($line in Get-Content $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
    $idx = $trimmed.IndexOf('=')
    if ($idx -lt 1) { continue }

    $key = $trimmed.Substring(0, $idx).Trim()
    $value = $trimmed.Substring($idx + 1).Trim()

    if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
      $value = $value.Substring(1, $value.Length - 2)
    }

    $result[$key] = $value
  }

  return $result
}

function Get-Value {
  param(
    [string]$Name,
    [hashtable]$ApiLocal,
    [hashtable]$Api,
    [hashtable]$WebLocal,
    [hashtable]$Web
  )

  $envValue = [Environment]::GetEnvironmentVariable($Name)
  if (-not [string]::IsNullOrWhiteSpace($envValue)) { return $envValue }
  if ($ApiLocal.ContainsKey($Name)) { return $ApiLocal[$Name] }
  if ($Api.ContainsKey($Name)) { return $Api[$Name] }
  if ($WebLocal.ContainsKey($Name)) { return $WebLocal[$Name] }
  if ($Web.ContainsKey($Name)) { return $Web[$Name] }
  return ''
}

function Is-HexAddress {
  param([string]$Value)
  return $Value -match '^0x[a-fA-F0-9]{40}$'
}

function Is-HexPrivateKey {
  param([string]$Value)
  return $Value -match '^0x[a-fA-F0-9]{64}$'
}

function Add-Check {
  param(
    [string]$Name,
    [bool]$Ok,
    [string]$Detail
  )
  return [pscustomobject]@{
    Check = $Name
    Status = $(if ($Ok) { 'PASS' } else { 'FAIL' })
    Detail = $Detail
  }
}

function Has-FilePathValue {
  param([string]$Value)
  return -not [string]::IsNullOrWhiteSpace($Value)
}

function Write-ApiEnvLocal {
  param(
    [string]$Path,
    [string]$Mode,
    [hashtable]$Values
  )

  $lines = @(
    '# Generated by scripts/testnet-readiness.ps1',
    "# Mode: $Mode",
    'PORT=3003',
    'API_KEY=',
    "USE_SNARKJS=$($Values['USE_SNARKJS'])",
    "SNARK_WASM_PATH=$($Values['SNARK_WASM_PATH'])",
    "SNARK_ZKEY_PATH=$($Values['SNARK_ZKEY_PATH'])",
    "SNARK_VKEY_PATH=$($Values['SNARK_VKEY_PATH'])"
  )

  if ($Mode -eq 'testnet') {
    $lines += @(
      "RPC_URL=$($Values['RPC_URL'])",
      "PRIVATE_KEY=$($Values['PRIVATE_KEY'])",
      "SBT_CONTRACT_ADDRESS=$($Values['SBT_CONTRACT_ADDRESS'])",
      "AGE_VERIFIER_ADDRESS=$($Values['AGE_VERIFIER_ADDRESS'])"
    )
  } else {
    $lines += @(
      'RPC_URL=',
      'PRIVATE_KEY=',
      'SBT_CONTRACT_ADDRESS=',
      'AGE_VERIFIER_ADDRESS='
    )
  }

  $content = ($lines -join "`n") + "`n"
  Set-Content -Path $Path -Value $content -Encoding utf8
}

function Write-WebEnvLocal {
  param(
    [string]$Path,
    [string]$Mode,
    [hashtable]$Values
  )

  $projectId = if ($Mode -eq 'testnet') { $Values['NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'] } else { '' }
  $lines = @(
    '# Generated by scripts/testnet-readiness.ps1',
    "# Mode: $Mode",
    "NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$projectId",
    'NEXT_PUBLIC_API_BASE_URL=http://localhost:3003'
  )

  $content = ($lines -join "`n") + "`n"
  Set-Content -Path $Path -Value $content -Encoding utf8
}

$apiLocal = Read-DotEnvFile -Path $apiEnvLocalPath
$api = Read-DotEnvFile -Path $apiEnvPath
$webLocal = Read-DotEnvFile -Path $webEnvLocalPath
$web = Read-DotEnvFile -Path $webEnvPath

$values = @{
  RPC_URL = Get-Value -Name 'RPC_URL' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  PRIVATE_KEY = Get-Value -Name 'PRIVATE_KEY' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SBT_CONTRACT_ADDRESS = Get-Value -Name 'SBT_CONTRACT_ADDRESS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  AGE_VERIFIER_ADDRESS = Get-Value -Name 'AGE_VERIFIER_ADDRESS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = Get-Value -Name 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  USE_SNARKJS = Get-Value -Name 'USE_SNARKJS' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_WASM_PATH = Get-Value -Name 'SNARK_WASM_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_ZKEY_PATH = Get-Value -Name 'SNARK_ZKEY_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
  SNARK_VKEY_PATH = Get-Value -Name 'SNARK_VKEY_PATH' -ApiLocal $apiLocal -Api $api -WebLocal $webLocal -Web $web
}

if (-not $values['USE_SNARKJS']) {
  $values['USE_SNARKJS'] = '0'
}

$checks = @()

if ($Mode -eq 'simulated') {
  $checks += Add-Check -Name 'RPC_URL empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['RPC_URL'])) -Detail 'Unset RPC_URL to force local simulation.'
  $checks += Add-Check -Name 'PRIVATE_KEY empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['PRIVATE_KEY'])) -Detail 'Unset PRIVATE_KEY to avoid on-chain tx signing.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS empty for simulated mode' -Ok ([string]::IsNullOrWhiteSpace($values['SBT_CONTRACT_ADDRESS'])) -Detail 'Unset SBT_CONTRACT_ADDRESS so /sbt/mint uses simulated response.'
} else {
  $checks += Add-Check -Name 'RPC_URL set' -Ok (-not [string]::IsNullOrWhiteSpace($values['RPC_URL'])) -Detail 'Required for testnet JSON-RPC provider.'
  $checks += Add-Check -Name 'PRIVATE_KEY set' -Ok (-not [string]::IsNullOrWhiteSpace($values['PRIVATE_KEY'])) -Detail 'Required for server-side signer.'
  $checks += Add-Check -Name 'PRIVATE_KEY format' -Ok (Is-HexPrivateKey $values['PRIVATE_KEY']) -Detail 'Expected 0x-prefixed 64-byte hex key.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS set' -Ok (-not [string]::IsNullOrWhiteSpace($values['SBT_CONTRACT_ADDRESS'])) -Detail 'Required to mint on-chain.'
  $checks += Add-Check -Name 'SBT_CONTRACT_ADDRESS format' -Ok (Is-HexAddress $values['SBT_CONTRACT_ADDRESS']) -Detail 'Expected 0x-prefixed 20-byte address.'
  $checks += Add-Check -Name 'WalletConnect project ID set' -Ok (-not [string]::IsNullOrWhiteSpace($values['NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'])) -Detail 'Required for web wallet connection UX.'

  if (-not [string]::IsNullOrWhiteSpace($values['AGE_VERIFIER_ADDRESS'])) {
    $checks += Add-Check -Name 'AGE_VERIFIER_ADDRESS format (optional)' -Ok (Is-HexAddress $values['AGE_VERIFIER_ADDRESS']) -Detail 'Optional, but must be valid address if set.'
  } else {
    $checks += Add-Check -Name 'AGE_VERIFIER_ADDRESS optional' -Ok $true -Detail 'Not set: /proof/verify-onchain will use local fallback verification.'
  }
}

$useSnark = $values['USE_SNARKJS'] -eq '1'
if ($useSnark) {
  $checks += Add-Check -Name 'SNARK_WASM_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_WASM_PATH']) -Detail 'Required for groth16 witness/proof generation.'
  $checks += Add-Check -Name 'SNARK_ZKEY_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_ZKEY_PATH']) -Detail 'Required proving key for groth16 fullProve.'
  $checks += Add-Check -Name 'SNARK_VKEY_PATH set when USE_SNARKJS=1' -Ok (Has-FilePathValue $values['SNARK_VKEY_PATH']) -Detail 'Required verification key for groth16 verify.'
}

Write-Host ""
Write-Host "LifePass Mode Checklist" -ForegroundColor Cyan
Write-Host "Mode: $Mode" -ForegroundColor Cyan
Write-Host ""
$checks | Format-Table -AutoSize

$failed = @($checks | Where-Object { $_.Status -eq 'FAIL' })

if ($Apply) {
  if ($failed.Count -gt 0) {
    Write-Host "" -ForegroundColor Red
    Write-Host "Cannot apply mode because checklist failed." -ForegroundColor Red
    exit 1
  }

  Write-ApiEnvLocal -Path $apiEnvLocalPath -Mode $Mode -Values $values
  Write-WebEnvLocal -Path $webEnvLocalPath -Mode $Mode -Values $values

  Write-Host "" -ForegroundColor Green
  Write-Host "Applied mode '$Mode':" -ForegroundColor Green
  Write-Host "- services/api/.env.local"
  Write-Host "- apps/web/.env.local"
}

Write-Host ""
if ($failed.Count -eq 0) {
  Write-Host 'Checklist status: READY' -ForegroundColor Green
  Write-Host 'Suggested next commands:' -ForegroundColor Green
  Write-Host '1. Set-Location services/api; npm run start'
  Write-Host '2. Set-Location apps/web; npm run dev'
  exit 0
}

Write-Host 'Checklist status: NOT READY' -ForegroundColor Yellow
Write-Host 'Fill missing values and re-run.' -ForegroundColor Yellow
exit 1
